#pragma once

#include "Character/Player/Player.h"
#include "Stage/Block/Block.h"
#include "Gimmick/Wall.h"
#include "Gimmick/Light.h"
#include "Gimmick/Invisiblefloor.h"
#include "Gimmick/PushBlock.h"
#include "Character/Enemy/Enemy.h"
#include "Character/Enemy/RealEnemy.h"
#include "Gimmick/Plate.h"
#include "Item/Heal.h"
#include "Item/ShadowHeal.h"
#include "TextObject.h"
#include "Gimmick/GoalPoint.h"